### ISSUE TITLE
能用，但是会丢消息

### ISSUE THREAD

**Issue by odinxu** [wadeee/dy-live-bullet-collect#2]
Chrome进直播间，观察弹幕信息，同时运行本程序，摆在一起对比观察。
发现会随机丢失弹幕信息。
![WechatIMG223](https://github.com/wadeee/dy-live-bullet-collect/assets/18024557/158db391-79db-4456-8652-931d721a8b86)

**Comment by wadeee** [comment]
感谢反馈，已修正bug
